### ISSUE TITLE
Implement Postgres

### ISSUE THREAD

**Issue by cisaacstern** [pangeo-forge/pangeo-forge-orchestrator#14]
This repo currently implements SQLite, but in order to deploy on Heroku we'll need to support Postgres.

**Comment by rabernat** [comment]
How different will it be? Do we need to explicitly test against Postgres? Or can we simply swap out a different backend in the deployments and have things just work?

**Comment by cisaacstern** [comment]
> How different will it be?

It will be quite similar. Though there are currently a few SQLite-specific assumptions hardcoded into the current repo, e.g.

https://github.com/pangeo-forge/pangeo-forge-orchestrator/blob/2b76858ce524417e5761e55241cd8804a939152e/pangeo_forge_orchestrator/database.py#L5-L6

which we'll want to generalize.

>  Do we need to explicitly test against Postgres?

The tests run fast enough that I was assuming we would, at least to begin with. (This could be a pytest.mark, so it only runs when called.) As I/we learn more about the differences (or lack thereof) between SQLite and Postgres, we may decide it's not necessary.

**Comment by rabernat** [comment]
Rather than installing postgres in our github workflows environment, perhaps we could accomplish this with [heroku ci](https://devcenter.heroku.com/articles/heroku-ci), coupled with [in-dyno databases](https://devcenter.heroku.com/articles/heroku-ci-in-dyno-databases). That also relates to #16.
