### ISSUE TITLE
What is the recipe_run.path attribute for?

### ISSUE THREAD

**Issue by rabernat** [pangeo-forge/pangeo-forge-orchestrator#23]
There is a comment in the recipe_run model about the `path` attribute:

https://github.com/pangeo-forge/pangeo-forge-orchestrator/blob/fb2250999905e9abdbbd1f0c29e6917a64796f00/pangeo_forge_orchestrator/models.py#L9-L18

```python
path: str  # Deterministic if in spec, but existing catalog not all in spec. 
```

I think we should remove this attribute. Regardless of whether existing data is in spec, I don't think it makes sense to have any concept of "path" in the recipe_run.

Instead, this information will show up in the `public_url` of the dataset table

```
Table dataset {
  id int [pk]
  name varchar
  produced_by int [ref: > recipe_run.id]
  type dataset_type
  public_url varchar
 }
```

(see [schema](https://dbdiagram.io/d/6192974202cf5d186b57003f))

My thinking was that bakeries would basically log where they put the data. Hopefully they will follow the spec, but even if not, we can still map from feedstock ➡️  recipe_run ➡️  dataset ➡️  url path where we can open the data.

If you agree I can make a PR to remove this field.

**Comment by cisaacstern** [comment]
This makes sense.

> we can still map from feedstock ➡️ recipe_run ➡️ dataset ➡️ url path

I'm trying to figure out if we need a `recipe_run.dataset` attribute (foreign key to the `dataset` table) to close this loop?

Without that, how do we get from `recipe_run` to `dataset`? There might be something obvious I'm overlooking.

**Comment by rabernat** [comment]
The produced_by field in the dataset table links to the recipe_runs table. SQL queries can join the tables.
