### ISSUE TITLE
Disallow certain fields for patch (i.e. update) requests

### ISSUE THREAD

**Issue by cisaacstern** [pangeo-forge/pangeo-forge-orchestrator#33]
> Oh, I see what you're going for with that edit in `model_builders` now. Seems like for both of these options, passing them doesn't raise an error, but also doesn't result in table fields being changed?

> _Originally posted by @cisaacstern in https://github.com/pangeo-forge/pangeo-forge-orchestrator/pull/32#discussion_r787974034_

Passing `id` or a field not present in the table should raise an error (not silently fail). This is probably possible with Pydantic.

**Comment by rabernat** [comment]
Also for create.
