### ISSUE TITLE
Repository's access policy 

### ISSUE THREAD

**Issue by andersy005** [pangeo-forge/pangeo-forge-orchestrator#67]
What is the repository's access policy? Access appears to be restricted to a few users. I want to open pull requests for local changes I've made to address various issues. 

```bash
> git push -u origin production-datasets
ERROR: Write access to repository not granted.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Cc @rabernat / @cisaacstern

**Comment by yuvipanda** [comment]
This repo is public now! \o/ #68 is closed.
