### ISSUE TITLE
Make this repository public

### ISSUE THREAD

**Issue by yuvipanda** [pangeo-forge/pangeo-forge-orchestrator#68]
This repo is currently private because it has some secrets that we don't want to leak. Let's work on making it public!

- [ ] Identify the various secrets in this repository, and where they are used
- [ ] Use [sops](https://github.com/mozilla/sops) to encrypt them so they can exist in the repo
- [ ] Expire existing secrets or rewrite repo history so they aren't available in history
- [ ] Figure out access control for who gets access to these secrets, and how they get access to it
- [ ] Make sure we won't accidentally leak them during the deploy process (if the deployment happens through GHA)
- [ ] Use https://github.com/yuvipanda/pre-commit-hook-ensure-sops to help prevent people from accidentally committing secrets

**Comment by yuvipanda** [comment]
Aaand this is public now!

![image](https://user-images.githubusercontent.com/30430/191821329-dd3c4e9b-6a98-41b3-99ea-b8d4f6582df9.png)

Thanks everyone :)

**Comment by cisaacstern** [comment]
Thanks @yuvipanda!
